### ISSUE TITLE
error: cannot join on columns 'elementId' x 'elementId':

### ISSUE THREAD

**Issue by dataneupane** [bergant/finstr#1]
Ran following: 
library(finstr)
inst<- "http://edgar.sec.gov/Archives/edgar/data/320193/000119312514383437/aapl-20140927.xml"

xbrl.vars<- xbrlDoAll(inst, verbose=TRUE)

st2013<-xbrl_get_statements(xbrl.vars)

Recevied following error 

Error: cannot join on columns 'elementId' x 'elementId': Can't join on 'elementId' x 'elementId' because of incompatible types (factor / integer) 
In addition: Warning message:
In semi_join_impl(x, y, by$x, by$y) :
  joining factors with different levels, coercing to character vector

**Comment by bergant** [comment]
For now use `options(stringsAsFactors = FALSE)` before calling `xbrDoAll`.
It is recommended in XBRL package (see `?xbrlDoAll`) so `finstr::xbrl_get_statements` expects data frames without factors.

**Comment by dataneupane** [comment]
Thanks it helped. Do you mind if I copy the issue and solution in stackoverflow?

**Comment by bergant** [comment]
No, I don't mind.

**Comment by dataneupane** [comment]
cool

**Comment by dataneupane** [comment]
http://stackoverflow.com/questions/31438961/edgar-finstr-error-cannot-join-on-columns-elementid-x-elementid-r/31438985#31438985
