### ISSUE TITLE
Installing finstr

### ISSUE THREAD

**Issue by brunosf2017** [bergant/finstr#3]
**I do not manage to install the package. I get the following reject:**

_* installing *source* package 'finstr' ...
Warning in file(file, if (append) "a" else "w") :
  cannot open file 'C:/Users/qtf/Documents/R/win-library/3.3/finstr/DESCRIPTION': No such file or directory
Error in file(file, if (append) "a" else "w") : 
  cannot open the connection
ERROR: installing package DESCRIPTION failed for package 'finstr'
_* removing 'C:/Users/ספז/Documents/R/win-library/3.3/finstr'
Error: Command failed (1)_

**Is there a way to solve the problem? Might this be due to changes in the R version?
Thank you**

**Comment by bergant** [comment]
Is it possible that the package is already loaded? Try restarting the R session and maybe close other processes (RStudio, R consoles) which might have used the package.

**Comment by brunosf2017** [comment]
No, it is not. I closed everything but it did not help. There is apparently a problem to install the DESCRIPTION package. Is there a way to install the package manually?

**Comment by bergant** [comment]
It is the DESCRIPTION file in the package. I don't know, maybe try to update devtools package?
And maybe delete the package files (if there are any) from your library directory...

**Comment by bergant** [comment]
It could be some encoding issue when devtools is using your user directory. Notice the difference in your error message (qtf vs ספז directory):

C:/Users/qtf/Documents/R/win-library/3.3/finstr/DESCRIPTION
C:/Users/ספז/Documents/R/win-library/3.3/finstr

**Comment by brunosf2017** [comment]
You are right. Thanks. I finally managed to install the package.

**Comment by bergant** [comment]
Glad to hear that!
